### ISSUE TITLE
Why only Backtick (`). Add support for single & double quotation marks (', ") also.

### ISSUE THREAD

**Issue by devseevali** [kaakaa/matterpoll-emoji#11]
Generally we use single or double quotation marks to highlight a phrase.

**Comment by kaakaa** [comment]
Thank you for a good suggestion!

Yeah, when writing sentences usually, I use single or double quotation rather than backtick.
But if single or double quotation were used as a character surrounding quotation sentence, I must escape quotations in question sentense. I don't prefer it.

e.g.:  `/poll "What do you gys wanna grab for \"lunch\"?" :pizza: :sushi: :fried_shrimp: :spaghetti: :apple:`

So I'm using Backtick as a character surrounding question sentence, because Backtick isn't used much.
And I did not think about supporting more characters.

But the above is just my own thoughts.
If you like using single & double quotations, I welcome your pull request.
