### ISSUE TITLE
Upload vendor directory to github

### ISSUE THREAD

**Issue by Hanzei** [kaakaa/matterpoll-emoji#54]
If we upload  `/vendor` to github, we wouldn't force people to install glide and matterpoll could be installed with `go get github.com/kaakaa/matterpoll-emoji`

**Comment by kaakaa** [comment]
I agree with no depending `glide` for any users because #34 was caused by `glide`.

But the size of `/vendor` is over 100MB. The size of our repo without `/vendor` is 263KB.
```
nemotoyuusukenoMacBook-Pro:matterpoll-emoji nemotoyuusuke$ du -sh ./vendor/
123M	./vendor/
nemotoyuusukenoMacBook-Pro:matterpoll-emoji nemotoyuusuke$ du -sh ../matterpoll-emoji/
123M	../matterpoll-emoji/
nemotoyuusukenoMacBook-Pro:matterpoll-emoji nemotoyuusuke$ rm -fr vendor/
nemotoyuusukenoMacBook-Pro:matterpoll-emoji nemotoyuusuke$ du -sh ./
268K	./
```

As It looks so huge, It's hard to agree with adding `/vendor` to our repository.
Is it popular to upload `/vendor`?

Alternatively, what do you think about starting to use `godep`?
Although users need to install `godep` `godep` is official tools.

**Comment by Hanzei** [comment]
The biggest directory in `/vendor` ist `/github.com/mattermost/platform` with 120MB. But we only need  `/model`. Is there any way to exclude certain directories from glide?

**Comment by Hanzei** [comment]
We could exclude the non needed directories in `/platform` via `.gitignore`. Then the size of `/vendor` goes down to 7,1MB.
