### ISSUE TITLE
details: Post http://localhost:8505/poll: address forbidden

### ISSUE THREAD

**Issue by diablotin84** [kaakaa/matterpoll-emoji#93]
Hi,

I have an error when i call /poll in my channel. In my log, i have this error:

Post http://localhost:8505/poll: address forbidden

My config.json:

{
  "host": "http://mattermost.<exemple.com>:8065",
  "listen": "localhost:8505",
  "token": "xxx",
  "user": {
   "id": "<my-user>",
   "password": "<my-password>"
 }
}

I run matterpoll with make run.

Tks for help and return.

**Comment by kaakaa** [comment]
Thank you for your report, @diablotin84!

`Post http://localhost:8505/poll: address forbidden` says that Mattermost cannot find application running on `http://localhost:8505`.

Is your matterpoll running in same host as Mattermost?

If `No`, could you try to set host name running matterpoll  instead of `localhost` to `Request URL` of Slach Command (e.g. `http://matterpoll-emoji.<example.com>:8505/poll`).

**Comment by diablotin84** [comment]
Hi,

Thks for return, yes same host :(
when i launch make run and launch after netstat -plunt command, i have:

tcp        0      0 127.0.0.1:8505          0.0.0.0:*               LISTEN      29340/main 

but always forbidden :(

**Comment by kaakaa** [comment]
Hmm..I would like to check another one.
Have you configure the `Allow untrusted internal conections to` option?

When matterpoll running in same host as Mattermost, I think that you have to add `localhost` to **(Mattermost) System Console** > **ADVANCED** > **Developer** > **Allow untrusted internal connections to** option.

If you do not do this, Mattermost seems to refuse the connection to the internal host(e.g. `localhost`).

**Comment by diablotin84** [comment]
ok thanks u very much it's solved :)

**Comment by kaakaa** [comment]
I'm glad to hear it :+1:
You're welcome!
